
spring:
  main:
    allow-circular-references: true
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static

server:
  error:
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always
    whitelabel:
      enabled: false
  port: 8081
